//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBLAPTOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDHB
    {
        public string maDH { get; set; }
        public string maCTDH { get; set; }
        public string maSP { get; set; }
        public Nullable<int> Giaban { get; set; }
        public Nullable<int> thanhtien { get; set; }
    
        public virtual DH DH { get; set; }
        public virtual Sanpham Sanpham { get; set; }
    }
}
