//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBLAPTOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHDN
    {
        public string maHDN { get; set; }
        public string maCTHDN { get; set; }
        public string maSP { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<decimal> Gianhap { get; set; }
    
        public virtual HDN HDN { get; set; }
        public virtual Sanpham Sanpham { get; set; }
    }
}
