//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBLAPTOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTSP
    {
        public string maSP { get; set; }
        public string maCTSP { get; set; }
        public string CPU { get; set; }
        public string RAM { get; set; }
        public string PIN { get; set; }
        public string HDD { get; set; }
        public string VGA { get; set; }
        public string Screem { get; set; }
    
        public virtual Sanpham Sanpham { get; set; }
    }
}
