//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBLAPTOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HDN()
        {
            this.CTHDNs = new HashSet<CTHDN>();
        }
    
        public string maHDN { get; set; }
        public string maNCC { get; set; }
        public string maNV { get; set; }
        public Nullable<decimal> Thanhtien { get; set; }
        public Nullable<System.DateTime> Ngaynhap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHDN> CTHDNs { get; set; }
        public virtual NCC NCC { get; set; }
        public virtual Nhanvien Nhanvien { get; set; }
    }
}
