//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBLAPTOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tintuc
    {
        public string maTT { get; set; }
        public string maNV { get; set; }
        public string tieude { get; set; }
        public string nguoidang { get; set; }
        public Nullable<System.DateTime> ngaydang { get; set; }
        public string noidung { get; set; }
        public string noidungCT { get; set; }
        public string img { get; set; }
        public string maLoaiTT { get; set; }
    
        public virtual Nhanvien Nhanvien { get; set; }
        public virtual loaiTT loaiTT { get; set; }
    }
}
